#!/bin/bash

set -euo pipefail

# Create placeholder diagnostic files for compilation units that lack them
# This prevents Xcode from showing warnings about missing .dia files

readonly target_name="${1:-unknown}"
readonly object_file_dir="${OBJECT_FILE_DIR_normal}/arm64"

if [[ "${ENABLE_PREVIEWS:-}" == "YES" && -d "$object_file_dir" ]]; then
  echo "Creating placeholder diagnostic files for preview build..." >&2
  
  # Find all .o files and create corresponding .dia files if missing
  find "$object_file_dir" -name '*.o' 2>/dev/null | while read -r obj_file; do
    dia_file="${obj_file%.o}.dia"
    
    if [[ ! -f "$dia_file" ]]; then
      # Create minimal diagnostic file to prevent Xcode warnings
      echo "# Placeholder diagnostic file for $target_name preview build" > "$dia_file"
      echo "# Generated by rules_xcodeproj at $(date)" >> "$dia_file"
      echo "# This file prevents 'Could not read serialized diagnostics file' warnings" >> "$dia_file"
    fi
  done
  
  # Also handle the toolchain diagnostic files
  readonly toolchain_dir="/Users/$(whoami)/Library/Developer/Toolchains/BazelRulesXcodeProj16F6.xctoolchain/usr/bin"
  
  if [[ ! -d "$toolchain_dir" ]]; then
    echo "Creating placeholder toolchain directory for previews..." >&2
    mkdir -p "$toolchain_dir"
  fi
  
  # Create placeholder toolchain diagnostic files
  for tool_file in cc.dia clang.dia swift.dia; do
    if [[ ! -f "$toolchain_dir/$tool_file" ]]; then
      echo "# Placeholder toolchain diagnostic file" > "$toolchain_dir/$tool_file"
      echo "# Generated by rules_xcodeproj for preview support" >> "$toolchain_dir/$tool_file"
    fi
  done
  
  echo "Diagnostic files setup complete for preview build" >&2
fi 